name: "Create Release"

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Set Version"
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: "Create release note"
        run: |
          echo "## Change Log" > note.txt
          echo "" >> note.txt

          git fetch origin --tags

          RECENT_TAG=$(git tag \
            --no-contains=$GITHUB_SHA \
            --sort="version:refname" \
            | tail -1)

          git log $RECENT_TAG..${{ env.VERSION }} \
            --pretty=format:"- %h : %s (by @%an)" >> note.txt

      - name: "Create release"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          gh release create ${{ env.VERSION }} \
            --title "Release ${{ env.VERSION }}" \
            --notes-file note.txt
