name: "Create Release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: "write"

jobs:
  create-release:
    name: "Create Release"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Set Version"
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: "Create release note"
        run: |
          echo "## Change Log" >> note.txt
          echo "" >> note.txt

          git fetch origin --tags

          RECENT_TAG=$(git tag \
            --no-contains=${{ env.VERSION }} \
            --sort=authordate | tail -1)

          git log $RECENT_TAG..${{ env.VERSION }} \
            --format='### %h : %s (by @%an)%n```%n%b```%n' \
            | sed -e :loop -e 'N; $!b loop' -e 's/```\n```//g' >> note.txt

      - name: "Create release"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          gh release create ${{ env.VERSION }} \
            --title "Release ${{ env.VERSION }}" \
            --notes-file note.txt
